/*#[binrw]
struct DatFile {
    version: String,
    float_ptr_terrain_tables: Vec<u32>,
    terrain_pass_graphic_pointers: Vec<u32>,
    terrain_restrictions: Vec<TerrainRestriction>,
    player_colours: Vec<PlayerColour>,
    sounds: Vec<Sound>,
    graphics: Optional<Vec<Graphic>>,
    terrain_block: TerrainBlock,
    random_maps: RandomMaps,
    effects: Vec<Effect>,
    unit_headers: Vec<UnitHeaders>,
    civs: Vec<Civ>,
    techs: Vec<Tech>,
    time_slice: u32,
    unit_kill_rate: u32,
    unit_kill_total: u32,
    unit_hit_point_rate: u32,
    unit_hit_point_total: u32,
    razing_kill_rate: u32,
    razing_kill_total: u32,
    tech_tree: TechTree,
}*/
